export default {
  HOME_PAGE_TITLE: "Welcome, what are you looking for today?",
  REGISTER_PAGE_TITLE:
    "To use this feature, you need to have an account. Log in with Facebook, Apple ID or create an account with your email address. Choose “register as a business” if you’re using the app for your company. ",
  //categories
  CATEGORIES: {
    VEHICLE: "Vehicle",
    ACCOMMODATION: "Accommodation",
    ELECTRONICS: "Electronics",
    SAVED: "Saved",
    OTHER: "Other",
    ALL: "All ads",
  },
  UPLOAD_IMAGE_TITLE: "Choose option for uploading",
  UPLOAD_FROM_GALLERY: "Upload from gallery",
  UPLOAD_VIDEO: "Upload video from gallery",
  ADD_PHOTOS: "Add Photos",
  UPLOAD_FROM_CAMERA: "Take a new photo",
  CANCEL: 'Cancel',
  LOGO_NAME: "",
  PROFILE: {
    HEADER: "Profile",
    MEMBER: "Member since",
    FREE_ADS: " You have 5 free ads",
    PHONE: " Phone",
    EMAIL: " Email",
    EDIT_PROFILE: "Edit your profile",
    ACCOUNT_DETAILS: "Account details",
    SETTINGS: "Settings",
    ACCOUNT_MANAGE: "Account management",
    SIGN_OUT: " Sign out",
    DELETE_ACCOUNT: " Delete account",
    READ_TERMS: "Read tearms and conditions",
  },
  BUTTONS: {
    SEE_ALL: "See all ads ",
    CONTINUE: "Continue",
    SAVE_CREATE: "Save and create profile",
    SAVE_UPDATE: "Save and update",
    CREATE_NEW_AD: "Create new ad",
    LOG_IN: "Log in",
    CONTACT_SELLER: "Contact seller and buy",
    SHOW_ALL: "Show Ads",
    CLEAR: "Clear",
    PUBLISH: "Pay and Publish",
    PREVIEW: "Preview",
    EDIT_AD: "Edit ad",
  },
  REGISTER: {
    TITLE: "Register with Email",
    REMEMBER_ME: "Remember me on this device",
    AGREE: "I agree on ",
    TERMS: "terms and conditions",
    FACEBOOK: "Log in with Facebook",
    APPLE_ID: "Log in with Apple ID",
    WITH_EMAIL: "Register with email",
    BUSINESS: "Register as a business",
    LOG_IN: "Log in with email",
  },
  FORM: {
    UPLOAD_TITLE: "Upload your company logo",
    FORMAT: "recommended format....",
    UPLOAD_LOGO: "Upload logo",
    MAX_SIZE: "Maximum file size 2 MB.",
    INSERT_IMAGE: "Maximum file size 2 MB.",
  },
  LABELS: {
    EMAIL: "Email",
    PASSWORD: "Password",
    NEW_PASSWORD: "New password",
    NAME: "Name",
    BUSINESS_NAME: "Business name",
    PHONE: "Phone",
    LOGO: "Upload your company logo",
  },
  PLACEHOLDERS: {
    EMAIL: "Enter your email adress",
    REPEAT_EMAIL: "Repeat email adress",
    PASSWORD: "Enter your password",
    NEW_PASSWORD: "Enter new password",
    REPEAT_NEW_PASSSWORD: "Repeat new password",
    REPEAT_PASSSWORD: "Repeat password",
    NAME: "Enter your name",
    SURNAME: "Enter your Surname",
    BUSINESS_NAME: "Name of your company",
    PHONE: "Enter your phone number",
    SEARCH: "Search",
    CATEGORY: "Category",
    SUB_CATEGORY: "Sub Category",
    AD_TITLE: "Title",
    AD_YOUTUBE: "Please insert youube link",
    AD_PRICE: "Price",
    AD_DESCRIPTION: "Description",
    AD_NAME: "Name",
    AD_PHONE: "Phone",
    AD_MILEAGE: "Mileage",
    AD_CITY: "City",
  },
  MODAL: {
    SUCCESS_TITLE: "Sucess headline",
    ERROR_TITLE: "No sucess headline",
    SUCCESS_TEXT:
      "Tellus, id lacinia risus dis porttitor tristique in. Libero, odio eget mi neque. Lobortis porttitor.",
    ERROR_TEXT:
      "Tellus, id lacinia risus dis porttitor tristique in. Libero, odio eget mi neque. Lobortis porttitor.",
  },
  ADS: {
    MY: "My Ads",
    MY_BUSINESS: "Our Ads",
    SELLER: "More ads",
    SELLER_BUSINESS: "Business’s ads",
    LATEST: "Latest",
    NO_RESULT: "No results to show",
    NO_RESULT_TEXT:
      "Try searching for something else, go back to home and choose another category or upload an ad by yourself!",
  },
  ADS_PAGE: {
    CATEGORY: "Category",
    VEHICLE: {
      FUEL: "Fuel",
      GEARBOX: "Gearbox",
      BRAND: "Brand",
      MODEL: "Model",
      MILAGE: "Milage",
      YEAR: "Model year",
    },
    ACCOMMODATION: {
      SQUARE_METER: "Square meter",
      BEDROOMS: "Bedrooms",
      SALE_RENT: "Sale/Rent",
      TYPE: "Type",
    },
    ELECTRONICS: {},
    OTHER: {},
    DESCRIPTION_BY_SELLER: "Description by seller",
    VIEWS: "Ad views",
  },
  FILTERS: {
    HEADER: "Filter",
    LATEST: "USE LATEST",
    LOCATION: "Location",
    CATEGORY: "Category",
  },
  CREATE_AD: {
    HEADER: 'Create ad',
    THANK_YOU_HEADER: 'Thank you!',
    THANK_YOU_MESSAGE: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eros ultricies eget vestibulum, interdum ' +
        'hac vitae at. Feugiat imperdiet augue ipsum tincidunt iaculis. Nec, adipiscing id a et ut tristique.',
    RETURN: 'Go back to homepage',
    ACCOMMODATION_SQUARE_METER: "Accommodation square meters"
  },
  SAVED: {
    HEADER: 'Saved',
    ADS: 'ADS',
    WATCHLIST: 'Watchlist',
    SAVED_ADS: 'saved ads'
  }
};
