export default {
  listData: [],
  adData: {},
  favoritesData: [],
  searchValue: "",
  adsCount: 0,
  order: "created_desc",
  sellerData: {},
  filters: {
    category_id: "",
    city: { id: "", name: "" },
    sub_category: { id: "", name: "" },
    vehicle_brand: { id: "", name: "" },
    vehicle_model: { id: "", name: "" },
    vehicle_year_max: "",
    vehicle_year_min: "",
    vehicle_milage_min: "",
    vehicle_milage_max: "",
    vehicle_fuel: "",
    vehicle_gearbox: "",
    accommodation_square_meter_min: "",
    accommodation_square_meter_max: "",
    accommodation_bedrooms_min: "",
    accommodation_bedrooms_max: "",
    accommodation_sale_rent: "",
    accommodation_type: "",
    price_min: "",
    price_max: "",
  },
  watchListData: [],
  watchListAdsCount: 0,
  locations: [],
  subCategories: [],
  latestFilters: [],
  savedFilters: []
};
